### ISSUE TITLE
Build error after creating `get /:username` URL parameter to create dynamic paths

### ISSUE THREAD

**Issue by ShawnHosea** [beginner-corp/begin-community#97]
Hey, Begin team! I found a bug that may affect all users. 

**Expected behavior**
Expected app to build and deploy to `staging` and `production` without error after provisioning a URL parameter that begins with just the colon.

**Description of bug**
This was logged in the Begin console at the `verify` step. 

```
Build failed!
Paths must start with a letter or number: get /:username
```

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Create a parameter in the `app.arc` file like so: `get /:username`
2. `arc init` to rehydrate file structure.
3. Commit snd push to Github
4. See error in the Begin console at the `verify` step.

**Screenshots**
Add screenshots to help explain your problem.
<img width="1084" alt="Screen Shot 2021-08-13 at 10 33 18 PM" src="https://user-images.githubusercontent.com/36789673/129449759-e9d9088c-a034-4044-8252-b2616c68b309.png">

**Additional context or notes**
Creating a URL parameter in this manner in Architect builds and deploys just fine. This error is specific to Begin.

**Comment by ryanblock** [comment]
We are relaxing this rule in the coming weeks with the next release of our build system!

However, in the mean time you should be able to use `get /*` to the same effect.

**Comment by ShawnHosea** [comment]
Cool! Thanks Ryan.
